input.reader: xevie
sample_theme: default
sound.loader: wav
# Sound ouput library: "mixed-alsa", "alsa" or "ao"
sound.output: default
# Parameter for alsa output, alternatively: plughw:0,0
sound.alsa.device: default
