
INSTALL(PROGRAMS ${CMAKE_BINARY_DIR}/${ANNOYME_EXECUTABLE} DESTINATION bin)
INSTALL(DIRECTORY ${CMAKE_SOURCE_DIR}/resources DESTINATION share/${PROJECT_NAME})
INSTALL(DIRECTORY ${CMAKE_SOURCE_DIR}/doc/man DESTINATION share)

SET(DOC_FILES
    ${CMAKE_SOURCE_DIR}/AUTHORS.txt
    ${CMAKE_SOURCE_DIR}/LICENSE.txt
    ${CMAKE_SOURCE_DIR}/README.txt
    ${CMAKE_SOURCE_DIR}/THANKS.txt
)
INSTALL(FILES ${DOC_FILES} DESTINATION share/${PROJECT_NAME}/doc)
