INCLUDE(InstallRequiredSystemLibraries)

SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "annoyme")
SET(CPACK_PACKAGE_VENDOR "Benjamin Peter <BenjaminPeter@arcor.de>")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.txt")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
SET(CPACK_PACKAGE_VERSION_MAJOR ${ANNOYME_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${ANNOYME_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${ANNOYME_VERSION_PATCH})
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")

SET(CPACK_STRIP_FILES ${ANNOYME_EXECUTABLE})
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_PACKAGE_EXECUTABLES ${ANNOYME_EXECUTABLE} ${ANNOYME_EXECUTABLE})
# Add package name to package file content
SET(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 1)
INCLUDE(CPack)
