
SET(ANNOYME_INSTALL_DIRECTORY ${CMAKE_SOURCE_DIR})
SET(ANNOYME_RESOURCE_DIRECTORY ${CMAKE_SOURCE_DIR}/resources)
SET(ANNOYME_SAMPLE_DIRECTORY ${CMAKE_SOURCE_DIR}/samples)
SET(ANNOYME_DEFAULT_CONFIG_NAME default_config.yaml)
SET(ANNOYME_CONFIG_NAME .annoyme)

CONFIGURE_FILE(${PROJECT_SOURCE_DIR}/src/config.h.in ${CMAKE_CURRENT_BINARY_DIR}/include/config.h)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR}/include/)

